[supervisord]
nodaemon=true
user=root

[program:xvfb]
command=/usr/bin/Xvfb :1 -screen 0 1400x900x24 -ac
autorestart=true
priority=1

[program:fix-cursor]
command=/bin/bash -c "sleep 2 && DISPLAY=:1 xsetroot -cursor_name left_ptr"
autorestart=false
priority=2
depends_on=xvfb

[program:vnc]
command=/usr/bin/x11vnc -display :1 -forever -shared -passwd password -cursor most
autorestart=true
priority=3
depends_on=xvfb

[program:aceest_ui]
command=/usr/local/bin/python aceest_ui.py
environment=DISPLAY=:1
autorestart=true
priority=4
depends_on=vnc

[program:novnc]
command=/usr/bin/websockify --web=/usr/share/novnc/ 6080 localhost:5900
autorestart=true
priority=5
depends_on=vnc