[supervisord]
nodaemon=true
user=root

[program:xvfb]
command=/usr/bin/Xvfb :1 -screen 0 1400x900x24
autorestart=true

[program:vnc]
command=/usr/bin/x11vnc -display :1 -forever -shared -nopw
autorestart=true
depends_on=xvfb

[program:aceest_ui]
command=/usr/local/bin/python aceest_ui.py
environment=DISPLAY=:1
autorestart=true
depends_on=vnc

[program:novnc]
command=/usr/bin/websockify --web=/usr/share/novnc/ 6080 localhost:5900
autorestart=true
depends_on=vnc